### ISSUE TITLE
Also require InsertEnter?

### ISSUE THREAD

**Issue by char101** [AndrewRadev/tagalong.vim#14]
Hi,

The description of this plugin only mentions `InsertLeave` but when I tried using it, I have to position the cursor inside the tag between the <> in normal mode, enter insert mode, only then will the closing tag be sychronized when exiting insert mode.

If I enter `insert` mode outside of the tag, then move the cursor inside the tag, and then make some changes, the closing tag is not synchronized when exitting insert mode.

Is this how the plugin should work or could it work with only `InsertLeave`?

**Comment by AndrewRadev** [comment]
The way the plugin works is by overwriting the built-in mappings. When you press `c` or `i` for instance, the plugin activates and takes a look under the cursor to see if there's a tag and where it's matching closing one is. On `InsertLeave`, it takes a look at the original tag position to see what change it needs to propagate.

Unfortunately, this means your use case isn't supported, as you've found out. If you have an idea how it could work, I could try it out, but I can't think of one. There's a `TextChanged` autocommand, and I think there's a way to monitor insertions, deletions, etc, but I think it would be much more complicated to work with that data.

I haven't mentioned `InsertEnter`, because the plugin doesn't use that event, instead it maps over the default keybindings. The "enter" autocommand is something I've never been able to get working, because the state of the cursor position is different depending on whether you use `c` or `i` for instance. I do have this line in the README (and in [the vim docs](https://github.com/AndrewRadev/tagalong.vim/blob/daeaa6ce332f78e47fdd6739fa4d21bf8d88f607/doc/tagalong.txt#L68-L70), under "Features and limitations":

> For all of these, the cursor needs to be within the `<>` angle brackets of the tag. If you change it from the outside, like with a `C` starting at the opening angle bracket, the plugin won't be activated.

I've also just pushed this particular case in the list of things that won't work. I'd rather not talk about `InsertEnter`, because it might be misleading, since the plugin doesn't use it. What do you think?

**Comment by AndrewRadev** [comment]
By the way, one method that could work is defining an insert-mode mapping that triggers tagalong explicitly, for instance:

``` vim
inoremap <silent> <c-t> <c-o>:call tagalong#Trigger()<cr>
```

With this, you could enter insert mode wherever you like, navigate in insert mode to the tag, and then before editing it, press `<c-t>` (for example) and then finish editing. When you exit insert mode, it should propagate the change. It requires manual intervention, and I guess you could also just exit and reenter insert mode :). But an insert-mode mapping might be more convenient. If you think this is something that could be useful to you, I could include it in the plugin with a configurable mapping.

**Comment by char101** [comment]
Thank your @AndrewRadev for the very detailed explanation. I understand now (a bit) on how this plugin works. I don't think there is any problem with it.

As for my usage style:

* I am a "notepad" style vim user, that is I use the arrow keys and mouse to move ;) so I find it difficult to have the cursor already positioned inside the tag in insert mode when I want to change it.
* Renaming tags is not something I do often, but it is annoying when I have to do it (that's why I much prefer pug syntax) so usually when I have to do it, I would have already forgotten any mapping I set before.

My initial assumption on how this plugin works was a simpler algorithm (1) on exiting the insert mode, look at the word under the cursor, (2) find the matching tag (3) replace the matching tag. Which is why I was wondering what is the need for the initial cursor position inside the tag.

**Comment by char101** [comment]
I just realized that after changing the tag, we need to parse the file to find the matching tag which is why it is harder. A simpler method is to know initially what tag is being changed, then we can simply replace the nearest matching tag.

**Comment by AndrewRadev** [comment]
Yes, that's exactly it -- when editing is done, there's no good way to find what the matching closing tag used to be. You could maybe try looking for an unmatched closing tag, but there might just be another one on the page. On the other hand, if you first find the closing before editing and remember it, you can apply the change on insert leave.
