### ISSUE TITLE
Get plugin to trigger automatically after renaming tag

### ISSUE THREAD

**Issue by Nishant-Pall** [AndrewRadev/tagalong.vim#16]
I'm a newbie around neovim plugins so please bear with me, I did `:PlugInstall` and tried testing it on a JSX file, but it didn't trigger the rename functionality of the closing tag if I rename the opening tag. Am I supposed to add some extra commands to my init.vim?

**Comment by AndrewRadev** [comment]
It should work out of the box, but there's a number of things that might be wrong. Could you show me a specific example code and the exact key sequence you used to edit it?

Additionally, in the file you edited, please execute `:set filetype` to report what the detected filetype was, and also `:map c` to see if the keys have been mapped successfully.

**Comment by Nishant-Pall** [comment]
> Additionally, in the file you edited, please execute :set filetype to report what the detected filetype was, and also :map c to see if the keys have been mapped successfully.
`:set filetype` gave typescriptreact as I'm working on a JSX file, `:map c` gave an output something like this
```
n  c           *@:<C-U>call tagalong#Trigger("c", v:count)<CR>                             
n  cS            <Plug>CSurround
n  cs            <Plug>Csurround

```

I'm not sure about the key sequence because I'm expecting the closing tag should change the name automatically as I edit the opening tag. Is this possible or do I have to specify a keymap to trigger the rename functionality

**Comment by AndrewRadev** [comment]
Both the filetype and the mapped key look fine, so the plugin is definitely loaded and *should* work.

> I'm not sure about the key sequence because I'm expecting the closing tag should change the name automatically as I edit the opening tag.

It should, but it may depend on how you edit it. There might be a bug -- maybe the component has some form that the plugin can't figure out. Maybe the way that you edit it is something that tagalong can't handle. This is why I'm asking you to just try a sequence of keys that doesn't work, any sequence, and tell me what it was that you tried. If it works for me, but doesn't work for you, we should look into your config and see what it could be that's different between our configs. If it doesn't work for me as well, that's something I can debug.

Here's an example:

``` tsx
let stuff = (
  <Foo>
    content
  </Foo>
);
```

If I put the cursor on the first letter of `Foo`, and I type `cwBar` and then exit insert mode, the closing tag gets renamed to `</Bar>` as well.

If I put the cursor at the end of the opening `Foo` and enter insert mode with `a`, I can type backspace 3 times, type `Bar` and then use the escape key to exit insert mode -- this also renames the closing tag for me.

Do both of these work for you or not? How are you editing the tags exactly is what I'm asking, since it makes a difference to what the plugin does. Is it possible you're not exiting insert mode when you're done typing (you mentioned you're a beginner in Vim, and might not be something you're used to yet)?

**Comment by Nishant-Pall** [comment]
> If I put the cursor on the first letter of `Foo`, and I type `cwBar` and then press escape to exit insert mode, the closing tag gets renamed to `</Bar>` as well.

I tried this, and it worked! I think the only way to achieve this by doing `cw` everytime as I couldn't get it to automatically rename if I do `dw` then switch to insert mode. Consequently, if I do `cw` after trying `dw` then insert mode which didn't work, then `cw` doesn't work as well. I hope I'm clear at this

> If I put the cursor at the end of the opening `Foo` and enter insert mode with `a`, I can type backspace 3 times, type `Bar` and then use the escape key to exit insert mode -- this also renames the closing tag for me.

This also seemed to work for me normally with some small issues.

Overall I believe there's a certain sequence that I need to follow. Say if I'm press delete 3 times on the first letter in insert mode, which is so no vim-type, it doesn't seem to trigger. If I follow your instructions, everything works fine. I mentioned I'm a beginner in Vim but maybe I should've said I'm an intermediate vim user. Anyways, thank you so much for your response. I appreciate your time and consideration

**Comment by AndrewRadev** [comment]
Yes, I see -- it's true, the plugin can't handle every method of changing the text. I've tried to explain what it can and can't do in the "Features and limitations" section: https://github.com/AndrewRadev/tagalong.vim#features-and-limitations. You could also take a look at which mappings the plugin hooks into: https://github.com/AndrewRadev/tagalong.vim#gtagalong_mappings.

It might work for more things in the future, but every new mapping carries a risk that something unexpected will break 😅. In any case, I'll close the issue for now.
