### ISSUE TITLE
Does not work when attributes (props) are on multiple lines

### ISSUE THREAD

**Issue by sangdth** [AndrewRadev/tagalong.vim#20]
When my JSX component has many props, it sometimes better to use multi-line, and tagalong stop working there.

It works well if everything stay on one line.

https://user-images.githubusercontent.com/1083478/168279128-413ed240-f8ce-4ba1-af1a-d213de068f14.mov

**Comment by AndrewRadev** [comment]
What mapping are you using to append to the `<Component` line? It seems I hadn't added `A` to the list of mappings to attach to, so that might have been what causes the problem, but I can't tell from the recording whether you type `a` or `A`. Could you try it now and see if you still have this issue?

**Comment by sangdth** [comment]
You're correct, I use `A` to append and it's fixed. Thank you very much! <3

**Comment by AndrewRadev** [comment]
A thing I still noticed as a potential issue is if the cursor is *outside* the tag, `A` still doesn't work, because it tries to "see" the tag at the cursor position before the jump. But I think there's nothing I can do about it, since it depends on when Vim throws these events. I'll do some thinking, but I feel it's also a bit of an edge case and maybe I'll just write it in the docs as a "known issue".

**Comment by sangdth** [comment]
I think using `A` outside of the tag, then slowly navigate back to the tag is NOT the popular choice if one wants to change the tag. So I agree that leaving it as edge case is OK, IMHO.
