### ISSUE TITLE
Using LSP (nvim-cmp) and tagalong.vim is breaking code

### ISSUE THREAD

**Issue by iduuck** [AndrewRadev/tagalong.vim#21]
Hello together, I just catched a bug, which is driving me crazy sometimes. 

When using the autocomplete of nvim-cmp, I am having a hard time to use the tagalong.vim package.

Is there any way to circumvent this one?

Edit: On the screen I am using "ESC" to exit the insert mode, which then replaces the `Link` with a `div`. Sometimes the full code is being unreadable

![CleanShot 2023-04-19 at 11 04 09](https://user-images.githubusercontent.com/325241/233025611-e4990632-d9b4-459d-b2ba-bb8a9b4b4d7d.gif)

**Comment by AndrewRadev** [comment]
Looking at the gif, the big thing that I see is that you start on line 15 and then move to line 16. I think that nvim-cmp is also adding a missing import, which shifts the code around and tagalong ends up looking at the wrong tag, because the lines shift under it. 

I'll see if I can figure out how to debug, but it might take a while -- I don't use neovim and I don't use LSP. My experience has generally been that they tend to be very aggressive in making changes to the buffer, which is both part of why I don't use this kind of thing, and why it might be hard to figure out the order of events and callbacks.

**Comment by iduuck** [comment]
What works is, that I dismiss the cmp dialog, and then just use a code action to import the missing import. But then, nvm. Thanks for the effort though.

**Comment by AndrewRadev** [comment]
Well, I'd like to take a look and see if there's a way to at least avoid messing the buffer up. I'll see if I can find the time for it.

**Comment by AndrewRadev** [comment]
I've pushed a branch called [`use-marks-for-positioning`](https://github.com/AndrewRadev/tagalong.vim/tree/use-marks-for-positioning), which should make sure that the tag changes are applied even if other lines are added. It's actually simpler in some ways, though it would mess up people's marks and I have to think about restoring.

For now, I'd like to understand how this affects the auto-import thing. I had a hard time replicating this, the best I could do was to stay in insert mode and go to the top of the buffer. Though there's one problem with that, I'd like to ignore it for now for testing purposes.

If you have the time and energy to help me out with testing, could you check this branch out and let me know if and how it works with nvim-cmp?

**Comment by iduuck** [comment]
Just switched to `nvim-ts-autotag`, (only) **until this is solved**, since I really like the work you are doing. 

Will try and report asap.

**Comment by fnune** [comment]
I'm seeing the same problem using https://github.com/neoclide/coc.nvim

I tried your branch https://github.com/AndrewRadev/tagalong.vim/tree/use-marks-for-positioning

It fixes the positioning problem, but for some reason it undoes the automatically-inserted import :/

**Comment by AndrewRadev** [comment]
> It fixes the positioning problem, but for some reason it undoes the automatically-inserted import :/

Yup, that's the problem I mentioned :)

> Though there's one problem with that, I'd like to ignore it for now for testing purposes.

I suppose that confirms that marks work, at least. The undoing is because there's a literal `undo` in the code, once you make the change, the plugin triggers an `undo` and applies both changes in both places. I remember I implemented it due to an issue, I don't remember what it was. I'll see if I can find the time this weekend to find it and shape up a more complete fix.

**Comment by AndrewRadev** [comment]
Turns out, marks won't help me avoid the issue, because marks seem to be maintained when *lines* are shifted, but the shifting columns when editing the opening tags are not kept.

I've created a new branch, [update-closing-position](https://github.com/AndrewRadev/tagalong.vim/tree/update-closing-position) which offsets the closing position of the end tag based on the difference of the original and current start tag position when exiting insert mode. It passes the tests and I think it should fix the issue fully, but I still need to reorganize the code a bit and think of other potential edge cases.

@fnune @iduuck Could you try that branch out and let me know if it seems to fix the problem?

**Comment by fnune** [comment]
Things worked fine with that branch for me!

**Comment by AndrewRadev** [comment]
I finally found some time to clean the code up a bit and I've merged this change to the main branch. With that, I'll close the issue, but let me know if this kind of thing happens again, or if the change causes some different problem.
