### ISSUE TITLE
Command `cw` does not work but instead it works like `w` command.

### ISSUE THREAD

**Issue by mechanicles** [AndrewRadev/tagalong.vim#4]
It looks like, in this plugin, we have overridden Vim's key.

`:nmap` gives me this result,

```
n  c  *@:call tagalong#Trigger()<CR><SNR>80_yank_with_key("c") 
```

My friend helped me to find out this issue and shared the following note with me.

`
Leader key prefix exists for this kind of remap, is for plugins authors or yourself don't map keybindings over vim keys
`

**Comment by AndrewRadev** [comment]
> It looks like, in this plugin, we have overridden Vim's key.

Yes, that's intentional. The goal of the plugin is to provide automatic updates of closing tags, which is why it overrides built-in mappings. If it used leader keys, it wouldn't really that big of an improvement over just using [vim-surround](https://github.com/tpope/vim-surround). You can find more details on how this works in [the README](https://github.com/AndrewRadev/tagalong.vim/blob/master/README.md#features-and-limitations).

The built-in mappings it changes are the following: `['c', 'C', 'v', 'i', 'a']`. If you'd like to disable the `c` and `C` keys in particular, you could put this in your vimrc:

``` vim
let g:tagalong_mappings = ['v', 'i', 'a']
```

There is currently no way to *change* the mappings, so maybe it could be convenient to provide that for people that still prefer using it, even if it's not hooking to the built-ins. What do you think of something like this:

``` vim
let g:tagalong_mappings = [{'c': '<leader>c'}, {'C': '<leader>C'}, 'v', 'i', 'a']
```

<hr>

Now, in this particular case, the problem is there seems to be *another* plugin attaching itself to a built-in. Tagalong tries to attach other mappings as well, so this seems to be breaking in this case. Could you try to figure out where this is coming from: `<SNR>80_yank_with_key("c")`? The first part, `<SNR>80_` is just a script-local identifier, so you could try grepping your vimfiles for `s:yank_with_key` or just `yank_with_key`. Let me know what you find. I could be able to work around the problem if I can see what that function is doing.

**Comment by mechanicles** [comment]
@AndrewRadev I will go through my vim files to search `yank_with_key` and will update you.

**Comment by mechanicles** [comment]
@AndrewRadev `yank_with_key` definition comes from this plugin https://github.com/maxbrunsfeld/vim-yankstack,

Also, after adding that line,

`let g:tagalong_mappings = [{'c': '<leader>c'}, {'C': '<leader>C'}, 'v', 'i', 'a']`

I get these errors,

<img width="445" alt="VIM_error" src="https://user-images.githubusercontent.com/77895/69493793-34845000-0ed9-11ea-8808-a5b0fb27d6a5.png">

Also, I do want to use this plugin https://github.com/maxbrunsfeld/vim-yankstack as well.

**Comment by AndrewRadev** [comment]
> Also, after adding that line,
> let g:tagalong_mappings = [{'c': '<leader>c'}, {'C': '<leader>C'}, 'v', 'i', 'a']
> I get these errors,

Yes, I was only asking what you thought of that interface, I hadn't implemented it yet. I've pushed some commits to implement it now. With this setting, the `<leader>c` and `<leader>C` keys should activate tagalong and, I *think* also yankstack. But either way, the native `c` and `C` keys will activate yankstack, so you should be fine either way.

Unfortunately, there's no way that I can see for me to have the native `c` and `C` keys work with both, for technical reasons (yankstack uses an `<expr>` mapping that I can't combine tagalong's mapping with).

But given you yourself suggest to use the leader key, this should be good enough for you?

**Comment by mechanicles** [comment]
@AndrewRadev I just updated this plugin, and it is working fine now with `<leader>c`. Even Yankstack plugin is also working fine. I appreciate your help 👍.  Thanks.
