### ISSUE TITLE
Breaks when setting whichwrap+=h,l

### ISSUE THREAD

**Issue by joerideg** [AndrewRadev/tagalong.vim#5]
Minimal vimrc to reproduce the issue:
```vim
" Using https://github.com/junegunn/vim-plug
call plug#begin('~/.config/nvim/plugged')
Plug 'AndrewRadev/tagalong.vim'
call plug#end()

set whichwrap+=h,l
```
I was trying this plugin and somehow it did not work. After slowly eliminating all my vim config it turned out to be caused by setting whichwrap. Any idea why this happends? (I couldnt even find the word 'whichwrap' in the repository)

**Comment by AndrewRadev** [comment]
Yeah, the problem is not me changing `whichwrap`, it's the fact that I don't, and rely on the default setting :). It often happens, I should really make a checklist. The particular problem is one place I do a `normal! l`, which should *not* go to the next line, but it does.

I've pushed a commit that should fix this. Could you confirm it works for you now?

**Comment by joerideg** [comment]
I will have a look!

**Comment by joerideg** [comment]
Yes it works now, thanks!
