### ISSUE TITLE
Input tag breaks this plugin

### ISSUE THREAD

**Issue by pkrumins** [AndrewRadev/tagalong.vim#6]
Hi Andrew,

Thanks once again for creating all these great plugins!

I was just writing a blog post about this plugin but run in an issue. If there's an `<input>` tag somewhere, then this plugin breaks. It does not replace the closing tag and leaves it as is.

Here's a minimal code snippet that shows this behavior:

```
<div class="hi">
  <input type="text">
</div>
```

If I put my cursor at `<div` and do a `cw` to a new tag name, then the closing tag does not get replaced.

Here's an even more minimal code snippet that shows this behavior:

```
<div>
  <input>
</div>
```

I hope you can reproduce this issue and this message was helpful. Have a great weekend!

Peter

**Comment by AndrewRadev** [comment]
Thank you for the kind words, Peter :).

Yes, I can reproduce the issue and I understand why it's happening. I seem to have made the assumption that single tags will be self-closed with a `/>`, and, unlike matchit, I'm checking for pairs of general nested tags, assuming they're well-paired.

I've made a change to the code to match the specific tags under the cursor, and your example works now. I was a bit nervous it'd break a bunch of things, but all the tests seem to be passing, so I guess it wasn't as big a deal as I thought it was. Or at least I hope so :).

I've pushed the fix to master. I'd appreciate if you could test it out and let me know if you see any different breakage because of it.

**Comment by pkrumins** [comment]
Hi Andrew,

Thanks for the quick fix!

I have just installed the latest version. I tested it on a couple of HTML files that I was having issues with earlier and it's working properly now.

I'm closing this issue but if anything comes up related to to this same issue, I'll reopen it.

Peter
