### ISSUE TITLE
Breaks 2cl / 3cw etc

### ISSUE THREAD

**Issue by callumacrae** [AndrewRadev/tagalong.vim#7]
I'm using the latest version of this plugin with nveovim v0.4.3.

When typing 2cl or 3cw or something like that, a new line is entered below the current line, the cursor is moved to it, and we enter insert mode, instead of the expected behaviour.

c2l and c3w still work, and removing the plugin fixes the issue.

**Comment by AndrewRadev** [comment]
Ah, this is a combination I hadn't considered.

It turned out to be surprisingly difficult to juggle these counts, but I think I managed to pull it off in a branch called [`fix-counts-for-actions`](https://github.com/AndrewRadev/tagalong.vim/tree/fix-counts-for-actions). I don't want to commit it to master yet, since I'd like to take the time to write some more tests both for this and one more edge case that doesn't seem to be tested right now. But could you test it out and tell me if it fixes your issue? Ideally, I'd appreciate it if you use it in the next couple of days too, let me know if you see any regressions in that branch.

**Comment by callumacrae** [comment]
yep that seems to fix the issue!

**Comment by AndrewRadev** [comment]
Cool, I've merged the change to master, so I'll consider this issue fixed for now. Let me know if you run into any regressions.

**Comment by callumacrae** [comment]
thanks :)
